import React from "react";
import { Container, Row, Col, Button, Image } from "react-bootstrap";

function AboutSection() {
  return (
    <Container>
      <Col>
        <Row className="mt-5">
          <Col
            className="d-flex flex-column align-items-center justify-content-center"
            xs={12}
            md={7}
          >
            <p className="section-title">
              Unlock Your Potential: Explore, Learn, and Grow!
            </p>
            <p className="section-description">
              Welcome to the Learn section! Here, you can explore a wide range
              of educational content generated by artificial intelligence to
              enhance your knowledge and skills in various subjects. Whether
              you're a student, professional, or lifelong learner, our curated
              resources cover diverse topics to suit your interests and learning
              goals. Dive in and discover something new today!
            </p>
          </Col>
          <Col
            className="d-flex flex-column align-items-end justify-content-center"
            xs={12}
            md={5}
          >
            <Image src="images/Learning-bro 1.svg" alt="Placeholder" fluid />
          </Col>
        </Row>

        <Row className="mt-5">
          <Col
            className="d-flex flex-column align-items-start justify-content-center"
            xs={12}
            md={5}
          >
            <Image src="images/Exams-bro 1.svg" alt="Placeholder" fluid />
          </Col>
          <Col
            className="d-flex flex-column align-items-center justify-content-center"
            xs={12}
            md={7}
          >
            <p className="section-title">
              Challenge Accepted: Skill Testing Quizzes
            </p>
            <p className="section-description">
              Test your knowledge and skills with our Assessments feature! Take
              interactive multiple choice quizzes designed to challenge your
              understanding of key concepts in various subjects. Whether you're
              preparing for exams, evaluating your progress, or simply honing
              your expertise, our assessments provide a convenient way to gauge
              your comprehension and identify areas for improvement. Start
              assessing your abilities now and track your growth over time!
            </p>
          </Col>
        </Row>

        <Row className="mt-5">
          <Col
            className="d-flex flex-column align-items-center justify-content-center"
            xs={12}
            md={7}
          >
            <p className="section-title">Study Smart: Your Notes Companion</p>
            <p className="section-description">
              Unlock the power of comprehensive notes with our Notes tool!
              Access structured summaries and key insights on a wide range of
              topics to reinforce your learning and revision efforts. Whether
              you're reviewing important concepts, preparing for exams, or
              refreshing your memory, our curated notes offer a convenient
              reference to help you grasp complex ideas more effectively.
              Simplify your study routine and maximize your retention with our
              user-friendly notes repository.
            </p>
          </Col>
          <Col
            className="d-flex flex-column align-items-end justify-content-center"
            xs={12}
            md={5}
          >
            <Image src="images/Blogging-bro 1.svg" alt="Placeholder" fluid />
          </Col>
        </Row>

        <Row className="mt-5">
          <Col
            className="d-flex flex-column align-items-start justify-content-center"
            xs={12}
            md={5}
          >
            <Image
              src="images/Man thinking-bro 1.svg"
              alt="Placeholder"
              fluid
            />
          </Col>
          <Col
            className="d-flex flex-column align-items-center justify-content-center"
            xs={12}
            md={7}
          >
            <p className="section-title">
              Confidence Booster: Resolve Your Queries Here
            </p>
            <p className="section-description">
              Got questions? We've got answers! In the Doubts section, you can
              submit your queries and receive personalized assistance from our
              knowledgeable team of experts. Whether you're struggling with a
              specific concept, seeking clarification on a challenging topic, or
              simply curious about a subject, our dedicated support system is
              here to address all your doubts and inquiries. Don't let
              uncertainty hold you back submit your doubts today and embark on a
              journey of clarity and understanding!
            </p>
          </Col>
        </Row>
      </Col>
    </Container>
  );
}

export default AboutSection;
